// auth actions
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGOUT = 'SET_LOGOUT';
export const CLEAR_AUTH_DATA = 'CLEAR_AUTH_DATA';

// user actions
export const SET_FRIENDS_AND_CHANNELS = 'SET_FRIENDS_AND_CHANNELS';
export const SET_MESSAGES_IN_CHANNEL = 'SET_MESSAGES_IN_CHANNEL';
export const SET_MESSAGES_IN_DM = 'SET_MESSAGES_IN_DM';
export const SET_OPEN_CHANNEL = 'SET_OPEN_CHANNEL';
export const SET_OPEN_DM = 'SET_OPEN_DM';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const ADD_NEW_DM = 'ADD_NEW_DM';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const ADD_MESSAGE_IN_DM = 'ADD_MESSAGE_IN_DM';
export const ADD_MESSAGE_IN_CHANNEL = 'ADD_MESSAGE_IN_CHANNEL';
export const EDIT_MESSAGE_IN_DM = 'EDIT_MESSAGE_IN_DM';
export const EDIT_MESSAGE_IN_CHANNEL = 'EDIT_MESSAGE_IN_CHANNEL';
export const DELETE_MESSAGE_IN_DM = 'DELETE_MESSAGE_IN_DM';
export const DELETE_MESSAGE_IN_CHANNEL = 'DELETE_MESSAGE_IN_CHANNEL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const SET_TYPING_IN_CHANNEL = 'SET_TYPING_IN_CHANNEL';
export const SET_TYPING_IN_DM = 'SET_TYPING_IN_DM';
export const UNSET_TYPING_IN_CHANNEL = 'UNSET_TYPING_IN_CHANNEL';
export const UNSET_TYPING_IN_DM = 'UNSET_TYPING_IN_DM';
export const SET_TYPING_IN_OPEN_CHANNEL = 'SET_TYPING_IN_OPEN_CHANNEL';
export const SET_TYPING_IN_OPEN_DM = 'SET_TYPING_IN_OPEN_DM';
export const UNSET_TYPING_IN_OPEN_CHANNEL = 'UNSET_TYPING_IN_OPEN_CHANNEL';
export const UNSET_TYPING_IN_OPEN_DM = 'UNSET_TYPING_IN_OPEN_DM';
export const SET_UNREAD_CHANNEL = 'SET_UNREAD_CHANNEL';
export const SET_UNREAD_DM = 'SET_UNREAD_DM';
export const SET_READ_CHANNEL = 'SET_READ_CHANNEL';
export const SET_READ_DM = 'SET_READ_DM';

// general actions
export const SET_CHANNELS = 'SET_CHANNELS';
export const SET_USERS = 'SET_USERS';
export const CLEAR_GENERAL_DATA = 'CLEAR_GENERAL_DATA';